import path from 'path';
import fs from 'fs';
import { initDatabase, closeDatabase } from '../src/db/database';
import { missionRepository } from '../src/db/repositories/mission.repo';
import { conversationRepository } from '../src/db/repositories/conversation.repo';
import { messageRepository } from '../src/db/repositories/message.repo';
import { memoryRepository } from '../src/db/repositories/memory.repo';
import { mainAiService } from '../src/services/main-ai.service';
import { sideQuestService } from '../src/services/sidequest.service';
import { returnToMissionService } from '../src/services/return-to-mission.service';

async function runPhase4Verification() {
  console.log('=== THREADBACK Phase 4: Return to Mission & Context Sharing Live Verification ===\n');

  const testDbDir = path.resolve(__dirname, '..', 'data', 'test-phase4');
  fs.mkdirSync(testDbDir, { recursive: true });
  const testDbPath = path.join(testDbDir, 'phase4-verify.db');
  if (fs.existsSync(testDbPath)) fs.unlinkSync(testDbPath);

  closeDatabase();
  initDatabase(testDbPath);
  console.log('1. Test Database initialized at:', testDbPath);

  // 1. Create Mission & Main Conversation
  console.log('\n2. Creating Mission...');
  const { mission, mainConversation } = missionRepository.createMissionWithMainConversation(
    'Build a robust Go REST API with authentication and SQLite storage'
  );
  console.log(`   ✓ Mission created: ID=${mission.id}`);
  console.log(`   ✓ Main Conversation created: ID=${mainConversation.id}`);

  // 2. Initial Main AI Turn (Live Gemma Inference)
  console.log('\n3. Step 1: User chats with Main AI...');
  const mainTurn1 = await mainAiService.processChat({
    conversationId: mainConversation.id,
    message: 'How should we organize our HTTP handler routes in Go?',
  });
  console.log('   ✓ Main AI reply received:');
  console.log('     "' + mainTurn1.reply.trim().split('\n')[0] + '..."');

  const mainMsgsTurn1 = messageRepository.getMessagesByConversationId(mainConversation.id);
  console.log(`   ✓ Main conversation has ${mainMsgsTurn1.length} messages (1 user, 1 assistant)`);

  // 3. User branches off into SideQuest
  console.log('\n4. Step 2: User starts and explores a SideQuest...');
  const sideQuest = conversationRepository.createSideQuestConversation(
    mission.id,
    'JWT Authentication Middleware in Go'
  );
  console.log(`   ✓ SideQuest created: ID=${sideQuest.id}, Topic="${sideQuest.topic}"`);

  // SideQuest Chat (Live Gemma Inference)
  const sqTurn1 = await sideQuestService.processSideQuestChat({
    conversationId: sideQuest.id,
    message: 'Explain how to implement a JWT authentication middleware in Go using standard http.Handler wrappers. Show a code signature.',
  });
  console.log('   ✓ SideQuest AI reply received:');
  console.log('     "' + sqTurn1.reply.trim().split('\n')[0] + '..."');

  const sqMsgs = messageRepository.getMessagesByConversationId(sideQuest.id);
  console.log(`   ✓ SideQuest conversation has ${sqMsgs.length} messages`);

  // 4. Return to Mission (Live Synthesis with Gemma)
  console.log('\n5. Step 3: User requests Return to Mission...');
  const returnResult = await returnToMissionService.returnToMission(sideQuest.id);
  console.log('   ✓ Structured Learning Summary generated by Gemma:');
  console.log('     - Topic:', returnResult.summary.topic);
  console.log('     - Key Learnings:', returnResult.summary.keyLearnings);
  console.log('     - Decisions:', returnResult.summary.decisions);
  console.log('     - Useful Examples:', returnResult.summary.usefulExamples);
  console.log('     - Mission Relevance:', returnResult.summary.missionRelevance);
  console.log('     - Unresolved Questions:', returnResult.summary.unresolvedQuestions);

  // Check SQLite persistence of summary and memory
  const storedSummary = memoryRepository.getSideQuestStructuredSummary(sideQuest.id);
  if (!storedSummary) throw new Error('Structured summary was not persisted in sidequest_memories');
  console.log('   ✓ Stored in SQLite sidequest_memories successfully.');

  const missionMemory = memoryRepository.getMissionMemory(mission.id);
  console.log('   ✓ Mission Memory updated with decisions:', missionMemory?.decisions);

  // 5. Main AI Continues with Transferred Context (Live Gemma Inference)
  console.log('\n6. Step 4: Main AI continues mission with transferred SideQuest context...');
  const mainTurn2 = await mainAiService.processChat({
    conversationId: mainConversation.id,
    message: 'Now that we explored JWT middleware, how should we wire up authentication to protect our user routes?',
  });
  console.log('   ✓ Main AI response informed by SideQuest received:');
  console.log('     "' + mainTurn2.reply.trim().split('\n')[0] + '..."');

  // 6. Verify Isolation
  console.log('\n7. Step 5: Verifying strict history isolation...');
  const finalMainMsgs = messageRepository.getMessagesByConversationId(mainConversation.id);
  const finalSqMsgs = messageRepository.getMessagesByConversationId(sideQuest.id);

  console.log(`   ✓ Main conversation message count: ${finalMainMsgs.length} (expected 4: 2 user, 2 assistant)`);
  console.log(`   ✓ SideQuest conversation message count: ${finalSqMsgs.length} (expected 2: 1 user, 1 assistant)`);

  if (finalMainMsgs.length !== 4) {
    throw new Error(`Expected 4 messages in Main AI conversation, got ${finalMainMsgs.length}`);
  }
  if (finalSqMsgs.length !== 2) {
    throw new Error(`Expected 2 messages in SideQuest conversation, got ${finalSqMsgs.length}`);
  }

  // Ensure no SideQuest messages leaked into Main AI message rows
  for (const msg of finalMainMsgs) {
    if (msg.content.includes('Explain how to implement a JWT authentication middleware in Go using standard http.Handler wrappers')) {
      throw new Error('Leakage detected: raw SideQuest user message found in Main AI conversation!');
    }
  }
  console.log('   ✓ ZERO history leakage verified: SideQuest messages were NOT appended to Main AI history.');

  // 7. Verify Deduplication on subsequent turn
  console.log('\n8. Step 6: Verifying deduplication (no repeated raw SideQuest summary injection)...');
  const unincorporated = memoryRepository.getUnincorporatedSideQuestSummaries(mission.id);
  console.log(`   ✓ Unincorporated summaries remaining for this mission: ${unincorporated.length} (expected 0)`);
  if (unincorporated.length !== 0) {
    throw new Error('SideQuest summary was not marked incorporated after Main AI interaction!');
  }

  closeDatabase();

  // Clean up scratch db
  if (fs.existsSync(testDbPath)) fs.unlinkSync(testDbPath);
  if (fs.existsSync(`${testDbPath}-wal`)) fs.unlinkSync(`${testDbPath}-wal`);
  if (fs.existsSync(`${testDbPath}-shm`)) fs.unlinkSync(`${testDbPath}-shm`);
  if (fs.existsSync(testDbDir)) fs.rmdirSync(testDbDir);

  console.log('\n=== All Phase 4 Live Verifications PASSED Successfully! ===');
}

runPhase4Verification().catch((err) => {
  console.error('Phase 4 verification failed:', err);
  process.exit(1);
});
